Update terms.md
emo-bon/emo-bon.github.io pull request #15
Opened 2024-12-06 14:04 UTC by mpo-vliz

some extra suggestions in light of https://github.com/emo-bon/emo-bon.github.io/issues/13

2025-01-03 12:50 UTC, laurianvm requested changes

2025-01-03 12:50 UTC, laurianvm commented on docs/terms.md
> +| **Sampling event** | A sampling action performed at a particular observatory at a specific time, resulting in the collection of one or more samples. Typically has some otyher measurements of the en
typo: otyher --> other

2025-01-03 12:50 UTC, laurianvm commented on docs/terms.md
> +| **DVC Stub File** | Inside our datamanagement solution we make use of [dvc.org](dvc.org) to connect our "EMO BON Repositories" (git based) to extera=nal large file storage locations.  This is to ov
typo: extera=nal --> external

2025-01-03 12:50 UTC, laurianvm commented on docs/terms.md
> +| **EMO BON RO-Crate** | EMO BON RO-Crates contain data associated with either: logsheets from observatories, MetaGOflow runs, sequencing metadata. Usually our RO-Crates map one-to-one to single repo
typo: identifiyin --> identifying
(unless you want to go for a "swag" connotation)

2025-01-03 13:20 UTC, laurianvm approved these changes

2025-01-06 15:30 UTC, marc-portier commented
@kmexter ok for me to merge?

2025-01-06 15:33 UTC, kmexter commented
yes

2025-02-01 06:08 UTC, merged